# Generated by Django 5.1.7 on 2025-03-21 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_table_alter_borrowedbooks_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbooks',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowedbooks',
            old_name='user_id',
            new_name='user',
        ),
    ]
